# Generated by Django 3.2.25 on 2024-04-18 16:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp01', '0002_alter_board_filesize'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('udx', models.AutoField(primary_key=True, serialize=False)),
                ('board_idx', models.IntegerField()),
                ('writer', models.CharField(max_length=50)),
                ('content', models.TextField()),
                ('post_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
    ]
