# Generated by Django 3.2.25 on 2024-04-18 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp01', '0003_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='udx',
            new_name='idx',
        ),
    ]
